version: '3.7'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: uwsgi /app/config/uwsgi.ini
    ports:
      - 8000:8080
    environment:
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - DEBUG=0
      - SECRET_KEY=test
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
