version: '3.7'

services:
  db:
    image: postgres:14.1-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432

volumes:
  postgres_data:
