# Generated by Django 3.1.1 on 2022-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220109_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Game name'),
        ),
    ]
